# Generated by Django 5.2.12 on 2026-03-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion',
            field=models.IntegerField(default=30),
        ),
    ]
