# Generated by Django 5.2.12 on 2026-04-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_reserva_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='duracion',
            field=models.IntegerField(default=60),
        ),
    ]
