# Generated by Django 5.2.12 on 2026-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
