# Generated by Django 5.2.12 on 2026-04-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_apellido_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='NotaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_historial', to='pacientes.paciente')),
            ],
        ),
    ]
